apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployments/
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployments/
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - tasks
            - worker
            - --loglevel=info
          image: kube-celery-dev-fork-celery_worker
          name: celery-worker 
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
