apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployments/
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployments/
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: flower
    spec:
      containers:
        - args:
            - celery
            - -A
            - tasks.app
            - flower
            - --port=5555
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
          image: flower
          name: flower
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
status: {}
