apiVersion: v1
kind: Pod
metadata: 
  name: flask-application
  labels: 
    name: celery-flask-pod
    app: celery-worker-app
spec: 
  containers: 
  - name: celery-flask-app
    image: raravindds/kube-celery-dev-fork-flask_application
    ports: 
      - containerPort: 5000
    
    

