apiVersion: v1
kind: Pod
metadata: 
  name: celery-redis-pod
  labels: 
    name: celery-redis-pod
    app: celery-worker-app
spec: 
  containers: 
  - name: celery-redis-app
    image: redis:6.2-alpine
    ports: 
      - containerPort: 6379

