apiVersion: v1
kind: Service
metadata: 
  name: flask-application
  labels: 
    name: celery-flask
    app: celery-worker-app
spec: 
  type: NodePort
  ports: 
  - port: 5005
    targetPort: 5005
    nodePort: 30000
  selector: 
    name: celery-flask-pod
    app: celery-worker-app