apiVersion: v1
kind: Pod
metadata: 
  name: celery-flower-pod
  labels: 
    name: celery-flower-pod
    app: celery-worker-app
spec: 
  containers: 
  - name: celery-flower-app
    image: raravindds/kube-celery-dev-fork-flower
    ports: 
      - containerPort: 5555