apiVersion: v1
kind: Pod
metadata: 
  name: redis
  labels: 
    name: celery-redis-pod
spec: 
  containers: 
  - name: celery-redis-app
    image: redis:6.2-alpine
    ports: 
      - containerPort: 6379


